const PAYMENT_PURPOSES = Object.freeze({
    WALLET_TOPUP: "WALLET_TOPUP",
    CREDIT_CHECK: "CREDIT_CHECK",
    MANDATE_CREATE: "MANDATE_CREATE",
});

const PAYMENT_STATUSES = Object.freeze({
    CREATED: "CREATED",
    PAID: "PAID",
    FAILED: "FAILED",
    CONSUMED: "CONSUMED",
});

const SETTING_KEYS = Object.freeze({
    CREDIT_CHECK_FEE: "CREDIT_CHECK_FEE",
    MANDATE_CREATE_FEE: "MANDATE_CREATE_FEE",
    MANDATE_INSTALLMENT_FEE: "MANDATE_INSTALLMENT_FEE",
});

module.exports = {
    PAYMENT_PURPOSES,
    PAYMENT_STATUSES,
    SETTING_KEYS,
};
