exports.MODES = ["UPI_AUTO_PAY", "NACH"];

exports.MANDATE_FREQUENCIES = [
    "ONCE",
    "DAILY",
    "WEEKLY",
    "MONTHLY",
    "YEARLY",
    "ADHOC",
];

exports.MANDATE_STATES = [
    "CREATED",
    "ACCEPTED",
    "ACTIVATED",
    "PAUSED",
    "HALTED",
    "CANCELLED",
    "TERMINATED",
    "COMPLETED",
];

exports.INSTALLMENT_STATES = [
    "CREATED",
    "TERMINATED",
    "COLLECTION_INITIATED",
    "COLLECTION_SUCCESS",
    "COLLECTION_FAILED",
    "SETTLEMENT_INITIATED",
    "SETTLEMENT_SUCCESS",
    "SETTLEMENT_FAILED",
];

/** Money collected from customer (still may be pending merchant settlement) */
exports.RECEIVED_INSTALLMENT_STATES = [
    "COLLECTION_SUCCESS",
    "SETTLEMENT_INITIATED",
    "SETTLEMENT_SUCCESS",
];

/** Money settled to merchant */
exports.SETTLED_INSTALLMENT_STATES = ["SETTLEMENT_SUCCESS"];

exports.PENDING_INSTALLMENT_STATES = ["CREATED", "COLLECTION_INITIATED"];

exports.FAILED_INSTALLMENT_STATES = [
    "COLLECTION_FAILED",
    "SETTLEMENT_FAILED",
];

exports.PARTY_TAGS = [
    "CUSTOMER_COLLECTION",
    "MERCHANT_SETTLEMENT",
    "CUSTOMER_CHARGE_COLLECTION",
    "MERCHANT_CHARGE_COLLECTION",
];

exports.WEBHOOK_ENTITY_TYPES = ["MANDATE", "INSTALLMENT", "UNKNOWN"];

exports.API_LOG_STATUS = ["SUCCESS", "FAILED", "ERROR"];
